name: New Example
description: Add a new example for an existing design pattern.
title: "[Example]: "
labels: new example
body:
  - type: input
    id: pattern_name
    attributes:
      label: Design Pattern Name
      description: Specify the design pattern to which this example belongs.
      placeholder: "e.g., Singleton, Factory, Observer."
  - type: textarea
    id: example_description
    attributes:
      label: Example Description
      description: Describe what your example does and why it is relevant.
      placeholder: "Explain the scenario and key components of the example."
  - type: textarea
    id: implementation_details
    attributes:
      label: Implementation Details
      description: Provide specific implementation notes, such as edge cases or dependencies.
      placeholder: "Explain how the example works and any important details."
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, resources, or links related to the example.
      placeholder: "Include code snippets, external links, or references here."
